services:
  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=yourpassword

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://admin:yourpassword@mongodb:27017/hotelmgmt?authSource=admin
      - PORT=8000
    depends_on:
      - mongodb
    volumes:
      - ./server:/app/server
      - ./dist:/app/dist

volumes:
  mongodb_data: